# Generated by Django 4.0.1 on 2022-02-05 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duarteshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('image', models.FileField(null=True, upload_to='products')),
                ('isOnSale', models.BooleanField(default=False)),
                ('isInStock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('addressline1', models.CharField(default='', max_length=100)),
                ('addressline2', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=40)),
                ('county', models.CharField(default='', max_length=15)),
                ('country', models.CharField(default='IRELAND', editable=False, max_length=7)),
                ('eircode', models.CharField(default='', max_length=7)),
                ('datetimeOrder', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('basketId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duarteshop.basket')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('basketId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duarteshop.basket')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duarteshop.product')),
            ],
        ),
    ]
