# Generated by Django 4.0.1 on 2022-04-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duarteshop', '0002_basket_product_order_basketitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
