# Generated by Django 4.0.1 on 2022-04-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duarteshop', '0003_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
